### ISSUE TITLE
Why is sountouch working as pseudo node?

### ISSUE THREAD

**Issue by floydback** [cutterbl/soundtouchjs-audio-worklet#1]
@cutterbl do you understand why SoundTouch can't work like a real node? Is there a fundamental problem?

**Comment by cutterbl** [comment]
@floydback I'm afraid you'll have to elaborate on what you mean by 'work like a real node'?

**Comment by floydback** [comment]
@cutterbl I mean AudioNode like GainNode or DealyNode. Now you need to connect/disconnect to the destination each time when play/stop audio. Is there a fundamental reason why PitchShifter cannot be connected to? Another drawback you can't use it with MediaElementSourceNode without decoding audio data.

**Comment by cutterbl** [comment]
@floydback As this is more a question (and one other's might ask), I [wrote this post in answer](https://cutterscrossing.com/development/ecmascript/webaudioapi/soundtouchjs/audioworklets/2020/05/14/why-is-soundtouch-working-as-a-pseudo-node/).
