### ISSUE TITLE
missing dist?

### ISSUE THREAD

**Issue by combs** [cutterbl/soundtouchjs-audio-worklet#2]
Hello! Thank you for making this!

First things first, I am a bit of a noob, and might be messing up something basic...

When I install with `npm install --save github:cutterbl/soundtouchjs-audio-worklet` in my project, the `dist/soundtouch-worklet.js` file doesn't seem to be present in `node_modules/@soundtouchjs/audio-worklet/`. 

I am cloning the repo and working on getting the build chain set up with `npm install` `npm run build` etc. and will then move the built files into `node_modules/@soundtouchjs/audio-worklet/`--is that the intended way to use this?

Very much appreciate any help you can offer. Thank you for making this module available! I'm excited to use it.

**Comment by cutterbl** [comment]
That's because you didn't install the distributed package (`npm i @soundtouchjs/audio-worklet`), but rather direct repo reference. You would have to go into the directory and run a build to create the `dist` folder.

**Comment by combs** [comment]
Thank you!
