### ISSUE TITLE
Fails with monaural (mono) sound

### ISSUE THREAD

**Issue by combs** [cutterbl/soundtouchjs-audio-worklet#3]
Hello again! Not sure this is something you need to support, but it might be worth a mention in the README.md: the worklet's `process()` assumes that there is stereo sound coming in, and fails during its loop with this if you give it mono:

```
Uncaught TypeError: Cannot set property '0' of undefined
```

seems possible to extend it to fix, I'll send in a PR if I end up going this route.

Thanks!

**Comment by cutterbl** [comment]
Interesting. You'll have to paste in a full stacktrace, as I can't tell if the error is ultimately coming from the worklet, or directly from `SoundTouchJS`.

**Comment by combs** [comment]
I'm having trouble getting a meaningful stack trace out of my webpack setup here, totally my fault, working to fix it. In the meantime I believe it's these lines in the worklet:

https://github.com/cutterbl/soundtouchjs-audio-worklet/blob/master/src/SoundTouchWorklet.js#L172-L179

it seems to be assuming number of channels:

```
    const left = outputs[0][0];
    const right = outputs[0][1];
```

Try feeding it a mono mp3, maybe you'll see the same thing?

**Comment by combs** [comment]
I may be making a mistake somewhere else, since the example code works with a monaural version of the provided file (despite above channel assumptions in the worklet).
